# Generated by Django 5.0.1 on 2024-02-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moru', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='footercontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
