# Generated by Django 4.2.4 on 2024-02-10 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moru', '0002_footercontact_alter_team_name_alter_team_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='footercontact',
            new_name='footer',
        ),
    ]
