# Generated by Django 4.2.4 on 2024-02-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moru', '0004_alter_tour_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='link',
        ),
    ]
