# Generated by Django 4.2.4 on 2024-02-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moru', '0006_itinerary'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('price', models.IntegerField(default=100)),
                ('image_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='itinerary',
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
