# Generated by Django 4.2.4 on 2024-02-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moru', '0007_hotels_delete_itinerary_alter_tour_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hotels',
            new_name='htels',
        ),
    ]
