# Generated by Django 4.2.4 on 2024-03-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moru', '0008_rename_hotels_htels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='image_url',
        ),
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to='media/'),
        ),
    ]
